osx_image: xcode11.4
language: swift

script:
  - make test

before_deploy:
  - make release
  - zip -r demure.zip demure start.sh stop.sh LICENSE Public Resources Sources/DemureAPI

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  file: demure.zip
  on:
    tags: true

after_deploy:
  - bundle exec pod trunk push Demure.podspec
